### ISSUE TITLE
Feature request: option to show seconds

### ISSUE THREAD

**Issue by junkyardsparkle** [quaddy-services/DynamicNightLight#7]
With an option to display time in HH:MM:SS format, this app would be perfect for the use case of taking a picture of the clock with a camera for the purpose of later synchronizing the times of photos with the times in a GPX file recorded by the phone.

**Comment by quaddy-services** [comment]
I will check that.

**Comment by quaddy-services** [comment]
You can check beta version via:
https://play.google.com/apps/testing/de.quaddyservices.dynamicnightlight

**Comment by quaddy-services** [comment]
In a few minutes the normal version has option to show seconds, too.

**Comment by junkyardsparkle** [comment]
Works great, thank you!
